# Generated by Django 5.1 on 2025-04-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kisaTanitim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklamaAdi', models.CharField(max_length=300, verbose_name='aciklamaAdi')),
                ('aciklama', models.TextField(verbose_name='aciklama')),
            ],
        ),
    ]
