# Generated by Django 5.1 on 2025-04-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Soru')),
                ('answer', models.TextField(verbose_name='Cevap')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
            ],
        ),
    ]
