# Generated by Django 5.1 on 2025-04-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_kisatanitim'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvukatOzgecmis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=200, verbose_name='Avukat Adı Soyadı')),
                ('fotoğraf', models.ImageField(upload_to='avukat_fotograflari/', verbose_name='Avukat Fotoğrafı')),
                ('biyografi', models.TextField(verbose_name='Biyografi')),
            ],
        ),
        migrations.CreateModel(
            name='BasindaBiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Haber Başlığı')),
                ('link', models.URLField(verbose_name='Haber Linki')),
                ('image', models.ImageField(blank=True, null=True, upload_to='basinda_biz/', verbose_name='Haber Resmi')),
            ],
        ),
        migrations.CreateModel(
            name='SertifikaBaro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='sertifika_barolar/', verbose_name='Baro veya Sertifika Logosu')),
                ('aciklama', models.CharField(max_length=200, verbose_name='Açıklama')),
            ],
        ),
        migrations.CreateModel(
            name='VizyonMisyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vizyon', models.TextField(verbose_name='Vizyon')),
                ('misyon', models.TextField(verbose_name='Misyon')),
            ],
        ),
        migrations.DeleteModel(
            name='kisaTanitim',
        ),
    ]
