# Generated by Django 5.1 on 2025-05-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_avukatozgecmis_basindabiz_sertifikabaro_vizyonmisyon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avukatozgecmis',
            old_name='fotoğraf',
            new_name='fotograf',
        ),
    ]
